version: "3"

networks:
  webapp:
    driver: bridge

services:
  app:
    build:
      context: .
      dockerfile: .docker/Dockerfile
    container_name: app
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    volumes:
      - .:/var/www/html
      - .docker/local.ini:/usr/local/etc/php/conf.d/local.ini:ro
      - .docker/nginx.conf:/etc/nginx/nginx.conf:ro
      - .docker/fpm-pool.conf:/etc/nginx/www.conf:ro
      - .docker/supervisord.conf:/etc/supervisor/conf.d/supervisord.conf:ro
    ports:
      - 8081:80
    depends_on:
      - mysql
    networks:
      - webapp

  mysql:
    image: mysql:8
    restart: unless-stopped
    tty: true
    volumes:
      - dbdata:/var/lib/mysql
    environment:
      MYSQL_DATABASE: webapp
      MYSQL_USER: user
      MYSQL_PASSWORD: user
      MYSQL_ROOT_PASSWORD: root
      SERVICE_NAME: mysql
    networks:
      - webapp

  phpmyadmin:
    image: phpmyadmin
    restart: unless-stopped
    ports:
        - 8082:80
    environment:
        - PMA_ARBITRARY=1
    networks:
        - webapp

volumes:
    dbdata:
